version: '3.6'
services:
  gitlab:
     image: 'gitlab/gitlab-ce:12.2.8-ce.0'
     container_name: gitlab
     environment:
       GITLAB_OMNIBUS_CONFIG: |
         external_url "http://REPLACEME.com/gitlab" # replace with a valid external url. Keep /gitlab !!!
     restart: always
     networks:
       - webnet
     ports:
       - '2222:22'
     volumes:
       - './gitlab/ssl:/etc/gitlab/ssl'
       - './gitlab/config:/etc/gitlab'
       - './gitlab/logs:/var/log/gitlab'
       - './gitlab/data:/var/opt/gitlab'
  jenkins:
    image: jenkins:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always
    networks:
      - webnet
  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    networks:
      - webnet
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - webnet
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      #- ./logs/nginx:/var/log/nginx
      #- ${NGINX_SSL_CERT:-./certs/self_signed_cert.pem}:/etc/nginx/ssl/server.crt # uncomment to use SSL
      #- ${NGINX_SSL_KEY:-./certs/self_signed_key.pem}:/etc/nginx/ssl/server.key   # uncomment to use SSL
    restart: always
    networks:
      - webnet
networks:
   webnet:
